### ISSUE TITLE
Display not shown

### ISSUE THREAD

**Issue by paolotormon** [shobhitpuri/custom-google-signin-button#13]
![custom-google-button-1](https://user-images.githubusercontent.com/61226023/84585686-dbfcac00-ae44-11ea-8999-397b8c322674.PNG)

![custom-google-button-0](https://user-images.githubusercontent.com/61226023/84585690-e5861400-ae44-11ea-928d-86c0ff9abae4.PNG)

It looks like this, I already added dependencies

**Comment by shobhitpuri** [comment]
Can you please share the details? i.e what OS level are your running the
app on? Also please share both of your build.gradle? I want to see the
target sdk etc to help replicate the issue. Thanks!

**Comment by paolotormon** [comment]
Hi Shobhit, I'm using Windows 10 and I'm running the app on API 29
![target-sdk](https://user-images.githubusercontent.com/61226023/84592179-4e39b480-ae76-11ea-8d3b-2871a0d5e21a.PNG)

**Comment by shobhitpuri** [comment]
Interesting! I tried to reproduce using the same settings but couldn't. 
Which Android device / Simulator and OS level you are running the code on?
 
Can you try with your settings by checking out the sample project in the master branch of this repo?

**Comment by paolotormon** [comment]
I'm using Nexus 5 API 29, although that button screenshot is from the .xml file's design view so the device is not the cause.

Okay I will try your suggestion

**Comment by shobhitpuri** [comment]
Sometimes the layout preview doesn't give the whole picture, that's why
asked. You see the above behaviour on the Nexus device as well as the
layout preview, right?

**Comment by kiduyu-klaus** [comment]
am getting the same layout also.

**Comment by rahulyadav97185966** [comment]
> ![custom-google-button-1](https://user-images.githubusercontent.com/61226023/84585686-dbfcac00-ae44-11ea-8999-397b8c322674.PNG)
> 
> ![custom-google-button-0](https://user-images.githubusercontent.com/61226023/84585690-e5861400-ae44-11ea-928d-86c0ff9abae4.PNG)
> 
> It looks like this, I already added dependencies

i think the android 4.1 has this issue, i am also getting same issue tried everything.

**Comment by rahulyadav97185966** [comment]
try to run your application in the mobile device the icon is visible when you run the application, it's just a bug in android studio.

**Comment by shobhitpuri** [comment]
Thanks for sharing your experience! I'll close issue for now then 👍
