### ISSUE TITLE
Does this library allowed to be used when shipping app to play store?

### ISSUE THREAD

**Issue by forceporquillo** [shobhitpuri/custom-google-signin-button#17]
Hello, I'd like to ask if using your library won't go against Google guidelines in terms of re-creating the sign-in button? I'm currently developing an app with Google sign-in integration and this will be ship to the play store.

Thank you!

**Comment by shobhitpuri** [comment]
From what I recall, they had branding guidelines when I wrote the library. You can adjust some things like text or size, but not other things like aspect ratio. From a quick Google search, I see this: https://developers.google.com/identity/branding-guidelines

**Comment by shobhitpuri** [comment]
@forceporquillo Let me know if you have further issues. I'm closing it for now. Thanks!

**Comment by forceporquillo** [comment]
@shobhitpuri Sorry for the late response. I'd already checked the link you'd provided.

PS. I'm currently using your library, and it's pretty convenient and easy to use. Thank you for your contribution!
