### ISSUE TITLE
 Customizing the Sign-In Button url return 404 error

### ISSUE THREAD

**Issue by fugogugo** [shobhitpuri/custom-google-signin-button#18]
the url of [Customizing custom button]( https://developers.google.com/identity/sign-in/android/custom-button) now return 404 error 

I think google moved the page somewhere but I can't seem to find it. Do you perhaps have any idea where it got moved?

**Comment by shobhitpuri** [comment]
Not sure. You can see from the web archive what it said: https://web.archive.org/web/20150926063503/https://developers.google.com/identity/sign-in/android/custom-button

Also, here are the branding guidelines: https://developers.google.com/identity/branding-guidelines#sign-in-button
