### ISSUE TITLE
Failed to resolve

### ISSUE THREAD

**Issue by gargVader** [shobhitpuri/custom-google-signin-button#20]
`Failed to resolve: com.shobhitpuri.custombuttons:google-signin:1.1.0`

**Comment by shobhitpuri** [comment]
Thanks for bringing that to notice. It might be since Bintray has been discontinued. We'll need to host it somewhere else.

**Comment by online-offl** [comment]
Any plan of hosting this?

**Comment by shobhitpuri** [comment]
@online-offl I want to but just not finding time. Feel free to fork it, and use it as a library project for the time being? Let me take a look at what's involved in hosting it. If you have any pointers, feel free to share, so that it's faster.

**Comment by shobhitpuri** [comment]
@online-offl Please see the new instructions in the README to add the library to your project. Let me know if there are any issues.
