### ISSUE TITLE
AndroidX support

### ISSUE THREAD

**Issue by vkotovv** [shobhitpuri/custom-google-signin-button#8]
Current version uses `android.support.v7` classes of the Support Library.
It would be great to provide a version with AndroidX support, so the users of the library could remove usage of [Jetifier](https://developer.android.com/jetpack/androidx#using_androidx) from the build.

**Comment by mohsiniqbalcui** [comment]
now fixed.

**Comment by shobhitpuri** [comment]
Closing the issue since the version 1.1.0 released supports AndroidX now.
